### ISSUE TITLE
win7系统安装完后JamTools软件打不开

### ISSUE THREAD

**Issue by HanKin2015** [fandesfyf/JamTools#10]
报错如下：
![image](https://user-images.githubusercontent.com/16322126/224875249-5420983e-077c-4d15-bf3b-e6ee4c02058f.png)

**Comment by fandesfyf** [comment]
@HanKin2015 你好, 感谢反馈, win7下运行已经修复, 可以从[这里](https://github.com/fandesfyf/JamTools/releases/tag/0.13.8B)下载重新打包好的安装程序
