### ISSUE TITLE
高分屏字很小

### ISSUE THREAD

**Issue by chenyue404** [fandesfyf/JamTools#18]
如题。我的屏幕是3840x2160，150%缩放。

还有，窗口右下角明明有可缩放的标志，但实际上并不能缩放。最大化的话，也只是窗口跑到屏幕左上角了而已……

**Comment by fandesfyf** [comment]
> 如题。我的屏幕是3840x2160，150%缩放。
> 
> 还有，窗口右下角明明有可缩放的标志，但实际上并不能缩放。最大化的话，也只是窗口跑到屏幕左上角了而已……

你好，感谢反馈这个问题，之前一直没有留意这个问题；

- 现在对于`高分辨率屏幕配置了dpi缩放，软件没有生效的问题`已经解决啦, 详情可以看[这个commit](https://github.com/fandesfyf/JamTools/commit/8faaa213bd247424a95e5518939c34395c835205)
- 软件已经重新打包上传，可以从[release](https://github.com/fandesfyf/JamTools/releases/tag/0.14.1B)中重新下载安装包
