### ISSUE TITLE
滚动截屏时，横向滚动后，exe就直接崩溃了

### ISSUE THREAD

**Issue by 1391735963** [fandesfyf/JamTools#26]
开始截屏，点击滚动截屏后，点击wps的excel的横向滚动条后，向右拖动后，exe程序就直接崩溃

https://github.com/fandesfyf/JamTools/assets/22694037/8c8f1529-75ed-432d-b474-b009a4c36bef

**Comment by fandesfyf** [comment]
你好，滚动截屏现在是还没有支持水平滚动的。。但是应该可以加上，等我有时间，下次一定(¬‿¬)
