### ISSUE TITLE
生成的MP4文件全是黑色的

### ISSUE THREAD

**Issue by mingming-ctr** [fandesfyf/JamTools#3]
能够正常运行了
只是生成的MP4文件有问题

下面是日志
-------------------------------------------------

"c:/work/JamTools\bin\win32/ffmpeg"   -thread_queue_size 16 -f gdigrab -rtbufsize 500M  -draw_mouse 1  -offset_x 0 -offset_y 0 -video_size 1366x768  -i desktop   -thread_queue_size 16 -f dshow -rtbufsize 50M -i audio="麦克风 (High Definition Audio Device)"  -qp 5  -vf scale=1366:-2  -r 30.0 -profile:v  high444 -level 5.1   -pix_fmt yuv420p -preset:v ultrafast -preset:a  ultrafast  
-vcodec libx264  C:/Users/m/Videos/Jam_screenrecord/2022-06-23_23.46.10.mp4 -y
[gdigrab @ 00000258f9899080] Capturing whole desktop as 1366x768x32 at (0,0)
[gdigrab @ 00000258f9899080] Stream #0: not enough frames to estimate rate; consider increasing probesize
[gdigrab @ 00000258f9899080] Could not find codec parameters for stream 0 (Video: bmp, none, 1006131 kb/s): unspecified size    
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, gdigrab, from 'desktop':
  Duration: N/A, bitrate: 1006131 kb/s
  Stream #0:0: Video: bmp, none, 1006131 kb/s, 29.97 fps, 1000k tbr, 1000k tbn
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, dshow, from 'audio=麦克风 (High Definition Audio Device)':
  Duration: N/A, bitrate: N/A
  Stream #1:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
Codec AVOption qp (use constant quantizer mode) specified for output file #0 (C:/Users/m/Videos/Jam_screenrecord/2022-06-23_23.46.10.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption profile () specified for output file #0 (C:/Users/m/Videos/Jam_screenrecord/2022-06-23_23.46.10.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Encoding preset) specified for output file #0 (C:/Users/m/Videos/Jam_screenrecord/2022-06-23_23.46.10.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #1:0 -> #0:0 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'C:/Users/m/Videos/Jam_screenrecord/2022-06-23_23.46.10.mp4':
  Metadata:
    encoder         : Lavf59.25.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc59.33.100 aac
size=       0kB time=06:06:16.90 bitrate=   0.0kbits/s speed=2.26e+04x    

[q] command received. Exiting.

[gdigrab @ 00000258f9899080] Thread message queue blocking; consider raising the thread_queue_size option (current value: 16)
size=      16kB time=06:06:16.95 bitrate=   0.0kbits/s speed=1.52e+04x    
video:0kB audio:15kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 6.473454%
[aac @ 00000258fb42dbc0] Qavg: 179.414

**Comment by mingming-ctr** [comment]
问题已经解决了
[用你编译好的文件](https://github.com/fandesfyf/JamTools/releases/download/0.13.6B/JamTools0.13.6BSetup_for_windows.exe)
直接复制bin/win32目录就可以了
怀疑是下载的[ffmpeg](https://ffmpeg.org/)不对。

希望能说明一下，下哪个版本的ffmpeg

**Comment by fandesfyf** [comment]
> 问题已经解决了 [用你编译好的文件](https://github.com/fandesfyf/JamTools/releases/download/0.13.6B/JamTools0.13.6BSetup_for_windows.exe) 直接复制bin/win32目录就可以了 怀疑是下载的[ffmpeg](https://ffmpeg.org/)不对。
> 
> 希望能说明一下，下哪个版本的ffmpeg

ffmpeg的版本可以通过` .\ffmpeg.exe -version`查看，其他平台也是这样的，有空我把我用的ffmpeg可执行文件也上传一下吧，之前是因为太大了经常上传失败所以就把它删了。。。
