### ISSUE TITLE
无法开机自启, 是否包含硬编码的绝对路径?

### ISSUE THREAD

**Issue by prcwak** [fandesfyf/JamTools#30]
开机自启是弹出错误提示, 其中包含一些本机不存在的路径和盘符.
![capture](https://github.com/fandesfyf/JamTools/assets/8850187/bbcdcccb-7376-41fa-a27e-b8c9ce2e3024)

**Comment by fandesfyf** [comment]
@prcwak 你好，感谢您的反馈，开机启动确实存在问题，但是不是硬编码的问题，cx_freeze打包是会将我机器上的路径打包进去，但是会在虚拟环境中解析，包含的路径不会影响正常运行；
- 根据报错的位置，发现是由于初始化时创建临时文件夹路径的问题
- 正常打开的情况下，会先将当前路径切换到系统临时文件夹之后再启动，创建j_temp文件夹用于存放一些临时文件，问题在于:提示拒绝访问的地方，是在切换路径之前创建目录的操作，会错误地在用户目录下创建一个临时文件夹，但是windows开机启动时，未登录的情况下这个目录还无法访问，导致启动出错
- 问题已经在这个commit修复：https://github.com/fandesfyf/JamTools/pull/31/commits/f58a2d7f3caf6b4304b55f41b1fbeab01ddf910b#diff-6a10765edccb5412b254b7901076af5009b8fdf569c0bd0b3dadc2ee56fee19f
- 根据使用习惯还增加了开机启动之后自动隐藏窗口到系统托盘，具体可以查看最新的main分支

**Comment by prcwak** [comment]
感谢
